/* logging.vapi generated by valac 0.48.17, do not modify. */

[CCode (cheader_filename = "ILogging.h")]
public interface ILogging : GLib.Object {
	public abstract void Log (string? log_domain, GLib.LogLevelFlags log_levels, string message);
}
[CCode (cheader_filename = "logging.h")]
public static GLib.Type register_plugin (GLib.Module module);
